

name: Unit-Test Backend

on:
  push:
    branches: 
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONDA_ENV_NAME: voice_smith
    strategy:
      matrix:
        python-version: [3.8.13]  
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env create -f ./backend/environment.yml
        $CONDA/bin/conda run --name $CONDA_ENV_NAME pip install -U pytest
    - name: Running PyTest Unit-Tests
      run:
        $CONDA/bin/conda run --name $CONDA_ENV_NAME pytest ./backend
